services:
  airflow-init:
    build: .
    container_name: airflow-init
    volumes:
      - ./src/job_plat/dags:/app/dags
      - ./data:/app/data
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: airflow db init

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - postgres
      - spark-master
    volumes:
      - ./src/job_plat/dags:/app/dags
      - ./data:/app/data
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
      - postgres
      - spark-master
    volumes:
      - ./src/job_plat/dags:/app/dags
      - ./data:/app/data
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
    command: airflow scheduler

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
