FROM apache/airflow:2.9.0

USER root

# Install Java & utilities
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk procps curl software-properties-common \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3

# Install Spark binaries
RUN curl -fsSL https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
    | tar -xz -C /opt/ \
    && ln -s /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark

ENV PATH="/opt/spark/bin:${PATH}"

# Create non-root user
RUN useradd -u 1000 -g 0 -m airflowuser
USER airflowuser

# Install Python packages
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.8.txt"

RUN pip install --no-cache-dir python-json-logger







#FROM apache/airflow:2.9.0

#USER airflow

#RUN pip install --no-cache-dir \
#    apache-airflow-providers-apache-spark \
#    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.12.txt"
