FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk curl && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_HOME=/opt/spark
ENV PATH="$SPARK_HOME/bin:$PATH"

RUN curl -fsSL https://archive.apache.org/dist/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz \
    | tar -xz && mv spark-3.5.0-bin-hadoop3 $SPARK_HOME

WORKDIR /opt/jobplat

COPY requirements.spark.txt .
RUN pip install --no-cache-dir -r requirements.spark.txt

# copy project metadata + code
COPY pyproject.toml README.md ./
COPY src/ ./src/

# install your package
RUN pip install -e . --no-deps

COPY settings.yaml /opt/jobplat/config/settings.yaml

CMD ["sleep", "infinity"]

