services:
  airflow-webserver:
    user: "${AIRFLOW_UID}:0"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: jobplat-airflow
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    environment:
      DATA_ROOT: /opt/jobplat/data
      METADATA_ROOT: /opt/jobplat/metadata
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 300
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: 300
      AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 300
      AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT: 300
      AIRFLOW__WEBSERVER__WORKERS: 1
      KUBECONFIG: /home/airflow/.kube/config
      PYTHONPATH: /opt/jobplat/src
      TRANSFORMERS_CACHE: /tmp/hf_cache
    volumes:
      - ./src:/opt/jobplat/src
      - ./src/job_plat/dags:/opt/airflow/dags
      - ./data:/opt/jobplat/data
      - ./logs:/opt/jobplat/logs
      - ./logs:/opt/airflow/logs
      - ./metadata:/opt/jobplat/metadata 
      - ./settings.yaml:/opt/jobplat/settings.yaml
      - ~/.kube/config:/home/airflow/.kube/config:ro
    ports:
      - "8080:8080"
    command: >
      bash -c "
      until airflow db check; do
        echo 'Waiting for DB...';
        sleep 5;
      done;
      export AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT=300 &&
      airflow webserver
      "
    networks:
      - jobplat

  airflow-scheduler:
    user: "${AIRFLOW_UID}:0"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: jobplat-airflow
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    environment:
      DATA_ROOT: /opt/jobplat/data
      METADATA_ROOT: /opt/jobplat/metadata
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      KUBECONFIG: /home/airflow/.kube/config
      PYTHONPATH: /opt/jobplat/src
      TRANSFORMERS_CACHE: /tmp/hf_cache
    volumes:
      - ./src:/opt/jobplat/src
      - ./src/job_plat/dags:/opt/airflow/dags
      - ./data:/opt/jobplat/data
      - ./logs:/opt/jobplat/logs
      - ./logs:/opt/airflow/logs
      - ./metadata:/opt/jobplat/metadata 
      - ./settings.yaml:/opt/jobplat/settings.yaml
      - ~/.kube/config:/home/airflow/.kube/config:ro
    command: >
      bash -c "
      until airflow db check; do
        echo 'Waiting for DB...';
        sleep 5;
      done;
      airflow scheduler
      "
    networks:
      - jobplat

  airflow-init:
    user: "${AIRFLOW_UID}:0"
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: jobplat-airflow
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      KUBECONFIG: /home/airflow/.kube/config
      PYTHONPATH: /opt/jobplat/src
    volumes:
      - ./src:/opt/jobplat/src
      - ./src/job_plat/dags:/opt/airflow/dags
      - ./settings.yaml:/opt/jobplat/settings.yaml
      - ~/.kube/config:/home/airflow/.kube/config:ro
    command: >
      bash -c "
      airflow db migrate &&
      airflow users list | grep admin || airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com
      "
    networks:
      - jobplat

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - jobplat

networks:
  jobplat:
    driver: bridge

volumes:
  postgres_data:

