FROM apache/airflow:2.9.3-python3.11

USER root

COPY dags/ /opt/airflow/dags/
RUN chown -R airflow: /opt/airflow/dags

COPY requirements.airflow.txt /requirements.airflow.txt
RUN chown airflow: /requirements.airflow.txt

USER airflow

RUN pip install --no-cache-dir -r /requirements.airflow.txt
