apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobplat-data-pv
spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

#  storageClassName: local-path

  hostPath:
    path: /tmp/jobplat-data

#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - k3d-jobplat-server-0
