apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobplat-data-pvc
  namespace: airflow

spec:
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  volumeName: jobplat-data-pv

######################################
#######################################

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jobplat-data-pvc
#  namespace: airflow

#spec:
#  accessModes:
#    - ReadWriteOnce

##  storageClassName: local-path

#  resources:
#    requests:
#      storage: 2Gi

#  volumeName: jobplat-data-pv

#######################################
#######################################

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jobplat-data-pvc
#  namespace: airflow
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: local-path
#  resources:
#    requests:
#      storage: 1Gi
