[project]
name = "real-time-job-market-intelligence-platform"
version = "0.1.0"
description = "A system that scrapes job postings, processes them at scale, extracts skills using NLP, and stores analytics in a data warehouse."
authors = [{ name = "ScriptFizz", email = "nsimamail@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11,<3.12"
keywords = ["data-engineering", "pyspark", "delta-lake", "mlops"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
dynamic = ["dependencies"]

[project.scripts]
job-plat = "job_plat.cli:app"

[tool.poetry]
packages = [{ include = "job_plat", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = ">=1.24.4,<2.0.0"
pandas = ">=2.3.3,<3.0.0"
pydantic = "^2.7"
pyspark = ">=3.5.1,<4.0.0"
python-dotenv = ">=1.0,<2.0"
python-json-logger = ">=2.0,<5.0"
pyyaml = ">=6.0.3,<7.0.0"
requests = ">=2.32.5,<3.0.0"
rich = "^13.7"
scikit-learn = ">=1.4,<2.0"
sentence-transformers = "^5.2.3"
torch = { version = "2.10.0+cpu", source = "pytorch-cpu" }
typer = ">=0.20.0,<0.21.0"
delta-spark = ">=3.3.0,<3.4.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.6.1"
black = ">=25.12.0,<26.0.0"
mypy = ">=1.19.0,<2.0.0"
pytest = ">=9.0.2,<10.0.0"
pytest-cov = ">=6.0,<8.0"
pre-commit = ">=4.5.0,<5.0.0"
ruff = ">=0.14.8,<0.15.0"
types-requests = ">=2.32.4.20250913,<3.0.0.0"
types-pyyaml = "^6.0.12.20260815"

[tool.poetry.group.cloud]
optional = true

[tool.poetry.group.cloud.dependencies]
google-cloud-storage = ">=3.0,<4.0"

[tool.poetry.group.airflow]
optional = true

[tool.poetry.group.airflow.dependencies]
apache-airflow = ">=2.10.5,<3.0.0"

[tool.poetry.group.viz]
optional = true

[tool.poetry.group.viz.dependencies]
ipykernel = ">=7.1.0,<8.0.0"
jupyterlab = "^4.1"
matplotlib = "^3.10.8"
seaborn = "^0.13.2"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
