apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: features-job-{{ ts_nodash }}
  namespace: default
spec:
  type: Python
  mode: cluster
  image: k3d-jobplat-registry:5000/jobplat-spark:latest #localhost:5000/jobplat-spark:latest #k3d-jobplat-registry:5000/jobplat-spark:latest
  imagePullPolicy: IfNotPresent

  mainApplicationFile: local:///opt/jobplat/src/job_plat/runners/ml/feature_runner.py

  #
  arguments:
    - --env
    - "{{ params.env }}" 
    - --execution-date
    - "{{ ds }}"
    - --config
    - /opt/jobplat/config/settings.yaml
  #

  sparkVersion: 3.5.0

  restartPolicy:
    type: Never

  sparkConf:
    spark.sql.shuffle.partitions: "4"
    spark.default.parallelism: "4"
    spark.ui.enabled: "false"
    spark.sql.adaptive.enabled: "false"
    spark.driver.memoryOverhead: "128m"
    spark.executor.memoryOverhead: "128m"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.sql.catalogImplementation: "in-memory"
    spark.local.dir: "/opt/jobplat/data/tmp"

  volumes:
    - name: config-volume
      configMap:
        name: jobplat-config

    - name: data-volume
      persistentVolumeClaim:
        claimName: jobplat-data-pvc

  driver:
    cores: 1
    memory: "384m"
    serviceAccount: spark

    env:
      - name: CONFIG_PATH
        value: /opt/jobplat/config/settings.yaml
      - name: DATA_ROOT
        value: /opt/jobplat/data
      - name: METADATA_ROOT
        value: /opt/jobplat/data/metadata
      #
      - name: ENV
        value: "dev"
      - name: EXECUTION_DATE
        value: "1970-01-01"
      - name: CONFIG_PATH
        value: /opt/jobplat/config/settings.yaml
      #

    volumeMounts:
      - name: config-volume
        mountPath: /opt/jobplat/config

      - name: data-volume
        mountPath: /opt/jobplat/data

  executor:
    cores: 1
    instances: 1
    memory: "384m"

    env:
      - name: CONFIG_PATH
        value: /opt/jobplat/config/settings.yaml
      - name: DATA_ROOT
        value: /opt/jobplat/data
      - name: METADATA_ROOT
        value: /opt/jobplat/data/metadata
      #
      - name: ENV
        value: "{{ params.env }}"
      - name: EXECUTION_DATE
        value: "{{ ds }}"
      #

    volumeMounts:
      - name: config-volume
        mountPath: /opt/jobplat/config

      - name: data-volume
        mountPath: /opt/jobplat/data

