apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: gold-job
  namespace: default
spec:
  type: Python
  mode: cluster
  image: k3d-jobplat-registry.localhost:5000/jobplat-spark:latest
  imagePullPolicy: Always

  mainApplicationFile: local:///opt/jobplat/src/job_plat/runners/data/gold_runner.py

  #
  arguments:
    - --env
    - $(ENV)
    - --execution-date
    - $(EXECUTION_DATE)
    - --config
    - /opt/jobplat/config/settings.yaml
  #

  sparkVersion: 3.5.0

  restartPolicy:
    type: Never

  volumes:
    - name: config-volume
      configMap:
        name: jobplat-config

    - name: data-volume
      persistentVolumeClaim:
        claimName: jobplat-data-pvc
  driver:
    cores: 1
    memory: "384m"
    serviceAccount: spark

    env:
      - name: CONFIG_PATH
        value: /opt/jobplat/config/settings.yaml
      - name: DATA_ROOT
        value: /opt/jobplat/data
      - name: METADATA_ROOT
        value: /opt/jobplat/data/metadata
      #
      - name: ENV
        value: "dev"
      - name: EXECUTION_DATE
        value: "1970-01-01"
      - name: CONFIG_PATH
        value: /opt/jobplat/config/settings.yaml
      #

    volumeMounts:
      - name: config-volume
        mountPath: /opt/jobplat/config

      - name: data-volume
        mountPath: /opt/jobplat/data

  executor:
    cores: 1
    instances: 1
    memory: "384m"

    env:
      - name: CONFIG_PATH
        value: /opt/jobplat/config/settings.yaml
      - name: DATA_ROOT
        value: /opt/jobplat/data
      - name: METADATA_ROOT
        value: /opt/jobplat/data/metadata
      #
      - name: ENV
        value: "dev"
      - name: EXECUTION_DATE
        value: "1970-01-01"
      - name: CONFIG_PATH
        value: /opt/jobplat/config/settings.yaml
      #

    volumeMounts:
      - name: config-volume
        mountPath: /opt/jobplat/config

      - name: data-volume
        mountPath: /opt/jobplat/data

